/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanKu;

import com.formdev.flatlaf.FlatLightLaf;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class layananFrame extends javax.swing.JFrame {

    /**
     * Creates new form layananFrame
     */
    public layananFrame() {
        initComponents();
    }
    
    static int total = 0;
    
    static String formatNumber(int nilai){
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator('.');
        DecimalFormat decimalFormat = new DecimalFormat("#,###", symbols);
        
        return "Rp " + decimalFormat.format(nilai);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxWin = new javax.swing.JCheckBox();
        cbxSC = new javax.swing.JCheckBox();
        cbxOhs = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbxWin.setForeground(new java.awt.Color(0, 0, 0));
        cbxWin.setText("LAYANAN WINDOWS 11");
        cbxWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxWinActionPerformed(evt);
            }
        });

        cbxSC.setForeground(new java.awt.Color(0, 0, 0));
        cbxSC.setText("SERVICE CENTER MICROSOFT");
        cbxSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSCActionPerformed(evt);
            }
        });

        cbxOhs.setForeground(new java.awt.Color(0, 0, 0));
        cbxOhs.setText("OFFICE OHS 2021");
        cbxOhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOhsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TOTAL BIAYA");

        labelHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelHarga.setForeground(new java.awt.Color(0, 0, 0));
        labelHarga.setText("Rp 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxWin)
                    .addComponent(cbxSC)
                    .addComponent(cbxOhs)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(labelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(cbxWin)
                .addGap(30, 30, 30)
                .addComponent(cbxOhs)
                .addGap(28, 28, 28)
                .addComponent(cbxSC)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelHarga))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxWinActionPerformed
        // TODO add your handling code here:
        if (cbxWin.isSelected()) {
            total += 200000;
//        labelHarga.setText("Rp. " +total);
        } else {            
            total -= 200000;
        }
        labelHarga.setText(formatNumber(total));
        
    }//GEN-LAST:event_cbxWinActionPerformed

    private void cbxOhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOhsActionPerformed
        // TODO add your handling code here:
        if (cbxOhs.isSelected()) {
            total += 100000;
//        labelHarga.setText("Rp. " + total);
        } else {            
            total -= 100000;
        }
        labelHarga.setText(formatNumber(total)); 

    }//GEN-LAST:event_cbxOhsActionPerformed

    private void cbxSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSCActionPerformed
        // TODO add your handling code here:
        if (cbxSC.isSelected()) {
            total += 500000;
//        labelHarga.setText("Rp. " +total);
        } else {            
            total -= 500000;
        }
        labelHarga.setText(formatNumber(total));

    }//GEN-LAST:event_cbxSCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new layananFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxOhs;
    private javax.swing.JCheckBox cbxSC;
    private javax.swing.JCheckBox cbxWin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHarga;
    // End of variables declaration//GEN-END:variables
}
